import * as React from 'react'; import { describe, expect, it, vi } from 'vitest'; import { render, screen } from '@testing-library/react'; import userEvent from '@testing-library/user-event'; import { Login } from './components/Login'; import { RoomList } from './components/RoomList'; import { SeatPanel } from './components/SeatPanel'; import { Composer } from './components/Composer'; import { MessageList } from './components/MessageList'; import { RoomView } from './components/RoomView'; import type { Approval, DiscoveredSession, Message, Room, Seat } from './types';
const room:Room={id:'r1',slug:'memright',title:'MemRight',objective:'Mirror fix',next_seq:3};
const seat:Seat={id:'s1',room_id:'r1',node_id:'n1',alias:'mac-claude',provider:'claude',session_ref:'thread-1',state:'idle',last_seen_ms:1,last_ack_seq:1};
const session:DiscoveredSession={node_id:'n2',node_name:'windows',provider:'codex',session_ref:'thread-2',title:'Mirror worker'};
const message:Message={id:'m2',room_id:'r1',seq:2,actor_id:'u',actor:'adrian',actor_kind:'human',kind:'chat',body:'hello',mentioned_seat_ids:[],created_at_ms:1,delivery_state:'queued'};
describe('Task 6 workflows',()=>{
 it('handles login success and failure',async()=>{const login=vi.fn().mockRejectedValueOnce(new Error()).mockResolvedValueOnce(undefined);render(<Login onLogin={login}/>);const u=userEvent.setup();await u.type(screen.getByLabelText('Admin token'),'wrong');await u.click(screen.getByRole('button',{name:'Sign in'}));expect(await screen.findByRole('alert')).toHaveTextContent('Invalid');await u.clear(screen.getByLabelText('Admin token'));await u.type(screen.getByLabelText('Admin token'),'right');await u.click(screen.getByRole('button',{name:'Sign in'}));expect(login).toHaveBeenLastCalledWith('right')});
 it('creates and archives rooms',async()=>{const create=vi.fn(),archive=vi.fn();render(<RoomList rooms={[room]} activeId="r1" onSelect={()=>{}} onCreate={create} onArchive={archive}/>);const u=userEvent.setup();await u.click(screen.getByLabelText('Create room'));await u.type(screen.getByLabelText('Slug'),'new-room');await u.type(screen.getByLabelText('Title'),'New room');await u.click(screen.getByRole('button',{name:'Create'}));expect(create).toHaveBeenCalledWith(expect.objectContaining({slug:'new-room'}));await u.click(screen.getByLabelText('Archive MemRight'));expect(archive).toHaveBeenCalledWith('r1')});
 it('attaches and detaches a discovered session',async()=>{const attach=vi.fn(),detach=vi.fn();render(<SeatPanel seats={[seat]} sessions={[session]} onAttach={attach} onDetach={detach}/>);const u=userEvent.setup();await u.click(screen.getByText('Attach session'));await u.type(screen.getByLabelText('Seat alias'),'windows-codex');await u.click(screen.getByRole('button',{name:/Mirror worker/}));expect(attach).toHaveBeenCalledWith(session,'windows-codex');await u.click(screen.getByLabelText('Detach mac-claude'));expect(detach).toHaveBeenCalledWith('s1')});
 it('inserts mention metadata and supports keyboard send',async()=>{const send=vi.fn(),handoff=vi.fn();render(<Composer seats={[seat]} online onSend={send} onHandoff={handoff}/>);const u=userEvent.setup();const box=screen.getByLabelText('Message room');await u.type(box,'Ask @mac');await u.click(screen.getByRole('option',{name:'@mac-claude'}));expect(screen.getByText('1 structured mention')).toBeVisible();await u.type(box,'review{Control>}');await u.keyboard('{Control>}{Enter}{/Control}');expect(send).toHaveBeenCalledWith(expect.stringContaining('@mac-claude'),['s1'])});
 it('renders optimistic and sequenced delivery state',()=>{render(<MessageList messages={[message,{...message,id:'m3',seq:3,pending:true,body:'optimistic'}]} hasOlder={false} onLoadOlder={vi.fn()}/>);expect(screen.getAllByText('queued')).toHaveLength(2);expect(screen.getByText('queued locally')).toBeVisible()});
 it('renders presence, authenticated approval controls, and handoff evidence',()=>{const approval:Approval={id:'a1',room_id:'r1',seat_id:'s1',description:'Run command',input_preview:'git push',decisions:['approve','reject'],state:'pending'};const handoff={...message,id:'h1',kind:'handoff' as const,handoff:{from_alias:'mac-claude',to_alias:'windows-codex',summary:'Continue mirror fix',evidence_refs:[{kind:'commit' as const,value:'abc123'}]}};render(<RoomView room={room} seats={[{...seat,state:'running'}]} sessions={[]} messages={[handoff]} approvals={[approval]} online onSend={vi.fn()} onLoadOlder={vi.fn()} onAttach={vi.fn()} onDetach={vi.fn()} onResolve={vi.fn()} onHandoff={vi.fn()}/>);expect(screen.getByLabelText('mac-claude running')).toBeInTheDocument();expect(screen.getByText('@mac-claude → @windows-codex')).toBeVisible();expect(screen.getByText(/abc123/)).toBeVisible();expect(screen.getByLabelText('approve Run command')).toBeEnabled()});
 it('disables approval and handoff controls offline',()=>{const approval:Approval={id:'a1',room_id:'r1',seat_id:'s1',description:'Run command',input_preview:'rm x',decisions:['approve'],state:'pending'};render(<RoomView room={room} seats={[seat]} sessions={[]} messages={[]} approvals={[approval]} online={false} onSend={vi.fn()} onLoadOlder={vi.fn()} onAttach={vi.fn()} onDetach={vi.fn()} onResolve={vi.fn()} onHandoff={vi.fn()}/>);expect(screen.getByRole('status')).toHaveTextContent('writes will replay');expect(screen.getByLabelText('approve Run command')).toBeDisabled();expect(screen.getByRole('button',{name:'Handoff'})).toBeDisabled()});
 it('requests older pages without replacing visible messages',async()=>{const load=vi.fn();render(<MessageList messages={[message]} hasOlder onLoadOlder={load}/>);await userEvent.click(screen.getByRole('button',{name:'Load older messages'}));expect(load).toHaveBeenCalledOnce();expect(screen.getByText('hello')).toBeVisible()});
 it('exposes accessible names and keyboard focus',async()=>{render(<Composer seats={[seat]} online onSend={vi.fn()} onHandoff={vi.fn()}/>);const field=screen.getByLabelText('Message room');expect(field).toBeVisible();await userEvent.tab();expect(field).toHaveFocus()})
});
