import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from './api'; import { offlineStore } from './offline'; import { Login } from './components/Login'; import { RoomList } from './components/RoomList'; import { RoomView } from './components/RoomView'; import type { Approval, DiscoveredSession, Message, Room, Seat, ServerEvent } from './types'; import './styles.css';
const emptyByRoom = <T,>(): Record<string,T[]> => ({});
export default function App(){
 const [auth,setAuth]=useState<'loading'|'out'|'in'>('loading'),[rooms,setRooms]=useState<Room[]>([]),[activeId,setActiveId]=useState<string>(),[messages,setMessages]=useState<Record<string,Message[]>>(emptyByRoom),[seats,setSeats]=useState<Record<string,Seat[]>>(emptyByRoom),[sessions,setSessions]=useState<DiscoveredSession[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[online,setOnline]=useState(navigator.onLine);
 const active=rooms.find(r=>r.id===activeId);
 const load=useCallback(async()=>{const rs=await api.rooms();setRooms(rs);setActiveId(x=>x||rs.find(r=>!r.archived_at)?.id);setSessions(await api.sessions());for(const room of rs.filter(r=>!r.archived_at)){const [ms,ss]=await Promise.all([api.messages(room.id),api.seats(room.id)]);setMessages(x=>({...x,[room.id]:ms}));setSeats(x=>({...x,[room.id]:ss}))}},[]);
 useEffect(()=>{api.me().then(()=>{setAuth('in');return load()}).catch(async()=>{setAuth('out');const cache=await offlineStore.loadSnapshot().catch(()=>undefined);if(cache){setRooms(cache.rooms);setMessages(cache.messages);setSeats(cache.seats);setApprovals(cache.approvals)}})},[load]);
 const handleEvent=useCallback((event:ServerEvent)=>{if(event.type==='seat.presence'){const seat=event.payload as unknown as Seat;setSeats(x=>({...x,[seat.room_id]:(x[seat.room_id]||[]).map(s=>s.id===seat.id?{...s,...seat}:s)}))}if(event.type==='delivery.state'){const p=event.payload as {room_id:string;message_id:string;state:Message['delivery_state']};setMessages(x=>({...x,[p.room_id]:(x[p.room_id]||[]).map(m=>m.id===p.message_id?{...m,delivery_state:p.state}:m)}))}if(event.type==='message.posted'){const m=event.payload as unknown as Message;setMessages(x=>({...x,[m.room_id]:[...(x[m.room_id]||[]).filter(old=>old.id!==m.id),m].sort((a,b)=>a.seq-b.seq)}))}if(event.type==='approval.requested')setApprovals(x=>[...x,event.payload as unknown as Approval])},[]);
 useEffect(()=>{if(auth!=='in')return;return api.events(handleEvent,async connected=>{setOnline(connected);if(connected){for(const write of await offlineStore.list().catch(()=>[])){try{await api.replay(write);await offlineStore.remove(write.request_id)}catch{break}}}})},[auth,handleEvent]);
 useEffect(()=>{if(auth==='in')offlineStore.saveSnapshot({rooms,messages,seats,approvals}).catch(()=>undefined)},[auth,rooms,messages,seats,approvals]);
 const actions=useMemo(()=>({create:async(input:Pick<Room,'slug'|'title'|'objective'>)=>{const room=await api.createRoom(input);setRooms(x=>[...x,room]);setActiveId(room.id);setMessages(x=>({...x,[room.id]:[]}));setSeats(x=>({...x,[room.id]:[]}))},archive:async(id:string)=>{const room=await api.archiveRoom(id);setRooms(x=>x.map(r=>r.id===id?room:r));if(activeId===id)setActiveId(rooms.find(r=>r.id!==id&&!r.archived_at)?.id)},send:async(body:string,mentioned_seat_ids:string[])=>{if(!active)return;const request_id=crypto.randomUUID();const optimistic:Message={id:request_id,room_id:active.id,seq:active.next_seq,actor_id:'human',actor:'adrian',actor_kind:'human',kind:'chat',body,mentioned_seat_ids,created_at_ms:Date.now(),pending:true,delivery_state:'queued'};setMessages(x=>({...x,[active.id]:[...(x[active.id]||[]),optimistic]}));if(!online){await offlineStore.enqueue({request_id,kind:'message',path:`/api/rooms/${active.id}/messages`,body:{body,mentioned_seat_ids,request_id},created_at_ms:Date.now(),attempt_at_ms:Date.now()});return}const posted=await api.postMessage(active.id,body,mentioned_seat_ids,request_id);setMessages(x=>({...x,[active.id]:(x[active.id]||[]).map(m=>m.id===request_id?posted:m)}))},older:async()=>{if(!active)return;const current=messages[active.id]||[];const older=await api.messages(active.id,current[0]?.seq);setMessages(x=>({...x,[active.id]:[...older,...current]}))},attach:async(session:DiscoveredSession,alias:string)=>{if(!active)return;const seat=await api.attachSeat(active.id,session,alias);setSeats(x=>({...x,[active.id]:[...(x[active.id]||[]),seat]}))},detach:async(id:string)=>{if(!active)return;await api.detachSeat(active.id,id);setSeats(x=>({...x,[active.id]:(x[active.id]||[]).filter(s=>s.id!==id)}))},resolve:async(approval:Approval,decision:string)=>{const resolved=await api.resolveApproval(approval.id,decision,crypto.randomUUID());setApprovals(x=>x.map(a=>a.id===approval.id?resolved:a))},handoff:async(target:Seat,summary:string)=>{if(!active)return;const source=(seats[active.id]||[])[0];if(!source)return;const posted=await api.handoff(active.id,source.id,target.id,summary,[],crypto.randomUUID());setMessages(x=>({...x,[active.id]:[...(x[active.id]||[]),posted]}))}}),[active,activeId,rooms,messages,seats,online]);
 if(auth==='loading')return <div className="loading" role="status">Loading Roundtable…</div>; if(auth==='out')return <Login onLogin={async token=>{await api.login(token);setAuth('in');await load()}}/>;
 return <div className="shell"><header className="topbar"><div className="wordmark">Round<span>table</span></div><span className={`connection ${online?'live':'lost'}`}>{online?'Hub live':'Offline'}</span><button onClick={async()=>{await api.logout();setAuth('out')}}>Sign out</button></header><div className="workspace"><RoomList rooms={rooms} activeId={activeId} onSelect={setActiveId} onCreate={actions.create} onArchive={actions.archive}/>{active?<RoomView room={active} seats={seats[active.id]||[]} sessions={sessions} messages={messages[active.id]||[]} approvals={approvals} online={online} onSend={actions.send} onLoadOlder={actions.older} onAttach={actions.attach} onDetach={actions.detach} onResolve={actions.resolve} onHandoff={actions.handoff}/>:<main className="empty"><h1>Create a room</h1><p>Attach a local session and begin a cross-device conversation.</p></main>}</div></div>
}
