#!/usr/bin/env bash
# Generate /etc/nginx/cloudflare-ips.conf — the allowlist that stops anyone reaching this origin
# without going through Cloudflare (and therefore without going through Cloudflare Access).
#
#   sudo ops/refresh-cloudflare-ips.sh && sudo nginx -t && sudo systemctl reload nginx
#
# Why this exists: Access is enforced at Cloudflare's edge. A request that arrives straight at the
# origin IP never passed through it. Verified 2026-07-26 — a Host-spoofed request to the origin
# returned 200 while the same URL through Cloudflare returned 302 to the Access login.
#
# Run it again whenever Cloudflare publishes new ranges. If legitimate traffic starts returning
# 403, a stale list here is the first thing to check.

set -Eeuo pipefail

OUT=/etc/nginx/cloudflare-ips.conf
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by ops/refresh-cloudflare-ips.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Source: https://www.cloudflare.com/ips-v4 and /ips-v6. Do not hand-edit."
  for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    curl -fsS --max-time 30 "$url" | while read -r cidr; do
      [ -n "$cidr" ] && echo "allow $cidr;"
      # set_real_ip_from must cover the same ranges or CF-Connecting-IP is not trusted.
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done
  done
} > "$TMP"

# Refuse to install a truncated list — that would 403 every visitor including Adrian.
# Measured 2026-07-26: 14 IPv4 + ~7 IPv6 = ~21 ranges. The floor is deliberately well below that
# (Cloudflare consolidates ranges occasionally) but high enough that a truncated or empty fetch —
# which would 403 every visitor including Adrian — cannot be installed.
count="$(grep -c '^allow ' "$TMP" || true)"
if [ "$count" -lt 15 ]; then
  echo "ERROR: only $count allow rules parsed; expected ~21. Refusing to install a partial list." >&2
  exit 1
fi

install -m 0644 "$TMP" "$OUT"
echo "wrote $OUT ($count allow rules)"
echo "now run: nginx -t && systemctl reload nginx"
